/**
 * Tool Selection Tests — Document Processing (12 tests) + Data Operations (10 tests).
 */

import type { ToolSelectionTest } from './types';

/** Document Processing — 12 tests covering the document server. */
export const documentProcessingTests: readonly ToolSelectionTest[] = [
  {
    id: 'ts-doc-001',
    category: 'document-processing',
    prompt: 'Extract the text from this PDF',
    context: ['I have a file at /Users/me/Documents/contract.pdf'],
    expectedTools: ['document.extract_text'],
    expectedParamKeys: { 'document.extract_text': ['path'] },
    difficulty: 'easy',
  },
  {
    id: 'ts-doc-002',
    category: 'document-processing',
    prompt: 'Convert this markdown file to PDF',
    context: ['Working with /Users/me/notes.md'],
    expectedTools: ['document.convert_format'],
    expectedParamKeys: { 'document.convert_format': ['path', 'target_format'] },
    difficulty: 'easy',
  },
  {
    id: 'ts-doc-003',
    category: 'document-processing',
    prompt: 'Compare the two versions of the contract',
    context: ['I have contract-v1.pdf and contract-v2.pdf in my Documents folder'],
    expectedTools: ['document.diff_documents'],
    expectedParamKeys: { 'document.diff_documents': ['path_a', 'path_b'] },
    difficulty: 'easy',
  },
  {
    id: 'ts-doc-004',
    category: 'document-processing',
    prompt: 'Create a DOCX from this text: "Quarterly Business Review - Q4 2024"',
    expectedTools: ['document.create_docx'],
    difficulty: 'easy',
  },
  {
    id: 'ts-doc-005',
    category: 'document-processing',
    prompt: 'Generate a PDF report with the following summary data',
    context: ['Revenue: $1.2M, Expenses: $800K, Net: $400K'],
    expectedTools: ['document.create_pdf'],
    expectedParamKeys: { 'document.create_pdf': ['content', 'output_path'] },
    difficulty: 'medium',
  },
  {
    id: 'ts-doc-006',
    category: 'document-processing',
    prompt: 'Fill in the tax form PDF with my information',
    context: ['The form is at /Users/me/Documents/tax-form-2024.pdf'],
    expectedTools: ['document.fill_pdf_form'],
    difficulty: 'medium',
  },
  {
    id: 'ts-doc-007',
    category: 'document-processing',
    prompt: 'Merge all the invoice PDFs into a single document',
    expectedTools: ['document.merge_pdfs'],
    difficulty: 'easy',
  },
  {
    id: 'ts-doc-008',
    category: 'document-processing',
    prompt: 'Read the data from the expenses spreadsheet',
    context: ['The file is expenses-2024.xlsx in my Documents folder'],
    expectedTools: ['document.read_spreadsheet'],
    expectedParamKeys: { 'document.read_spreadsheet': ['path'] },
    difficulty: 'easy',
  },
  {
    id: 'ts-doc-009',
    category: 'document-processing',
    prompt: 'Convert my Word document to HTML format',
    context: ['Working with /Users/me/Documents/proposal.docx'],
    expectedTools: ['document.convert_format'],
    expectedParamKeys: { 'document.convert_format': ['path', 'target_format'] },
    difficulty: 'easy',
  },
  {
    id: 'ts-doc-010',
    category: 'document-processing',
    prompt: 'What are the differences between the old and new employee handbook?',
    context: ['Files: handbook-2023.pdf and handbook-2024.pdf'],
    expectedTools: ['document.diff_documents'],
    difficulty: 'medium',
  },
  {
    id: 'ts-doc-011',
    category: 'document-processing',
    prompt: 'Create a nicely formatted PDF from my meeting notes markdown',
    expectedTools: ['document.create_pdf'],
    difficulty: 'easy',
  },
  {
    id: 'ts-doc-012',
    category: 'document-processing',
    prompt: 'Extract all the text from the scanned contract so I can search it',
    context: ['The scanned contract is at /Users/me/scanned-contract.pdf'],
    expectedTools: ['document.extract_text'],
    difficulty: 'easy',
  },
];

/** Data Operations — 10 tests covering the data server. */
export const dataOperationTests: readonly ToolSelectionTest[] = [
  {
    id: 'ts-data-001',
    category: 'data-operations',
    prompt: 'Export this data to a CSV file',
    context: ['I have a list of transactions I need saved'],
    expectedTools: ['data.write_csv'],
    difficulty: 'easy',
  },
  {
    id: 'ts-data-002',
    category: 'data-operations',
    prompt: 'Check for duplicate entries in this contacts list',
    expectedTools: ['data.deduplicate_records'],
    difficulty: 'easy',
  },
  {
    id: 'ts-data-003',
    category: 'data-operations',
    prompt: 'Run a query on the expenses database to find all entries over $500',
    expectedTools: ['data.query_sqlite'],
    expectedParamKeys: { 'data.query_sqlite': ['query'] },
    difficulty: 'medium',
  },
  {
    id: 'ts-data-004',
    category: 'data-operations',
    prompt: 'Save this transaction data to the SQLite database',
    expectedTools: ['data.write_sqlite'],
    difficulty: 'easy',
  },
  {
    id: 'ts-data-005',
    category: 'data-operations',
    prompt: 'Look for any anomalies or outliers in the sales data',
    expectedTools: ['data.summarize_anomalies'],
    difficulty: 'medium',
  },
  {
    id: 'ts-data-006',
    category: 'data-operations',
    prompt: 'Create a CSV report of all employees and their departments',
    expectedTools: ['data.write_csv'],
    difficulty: 'easy',
  },
  {
    id: 'ts-data-007',
    category: 'data-operations',
    prompt: 'Query the inventory database for items with stock below 10',
    expectedTools: ['data.query_sqlite'],
    difficulty: 'medium',
  },
  {
    id: 'ts-data-008',
    category: 'data-operations',
    prompt: 'Remove duplicate rows from the customer database',
    expectedTools: ['data.deduplicate_records'],
    difficulty: 'easy',
  },
  {
    id: 'ts-data-009',
    category: 'data-operations',
    prompt: "Are there any unusual patterns in this month's expense reports?",
    expectedTools: ['data.summarize_anomalies'],
    difficulty: 'medium',
  },
  {
    id: 'ts-data-010',
    category: 'data-operations',
    prompt: 'Insert these new vendor records into the procurement database',
    expectedTools: ['data.write_sqlite'],
    difficulty: 'medium',
  },
];
